{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Recipe API",
    "description" : "A simple API for managing recipes",
    "version" : "1"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/TOMCOOL/coolrecipes/1",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "http://localhost:5000"
  } ],
  "paths" : {
    "/users" : {
      "get" : {
        "summary" : "Get all users",
        "responses" : {
          "200" : {
            "description" : "Returns a list of all users",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new user",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Returns the newly created user",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}" : {
      "get" : {
        "summary" : "Get a user by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the user to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns the user with the specified ID",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "put" : {
        "summary" : "Update a user by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the user to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Returns the updated user",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}/recipes" : {
      "get" : {
        "summary" : "Get all recipes created by a user",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the user to get the recipes for",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns a list of all recipes created by the specified user",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Recipe"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/ingredients" : {
      "get" : {
        "summary" : "Get all ingredients",
        "responses" : {
          "200" : {
            "description" : "Returns a list of all ingredients",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Ingredient"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new ingredient",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/IngredientInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Returns the newly created ingredient",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ingredient"
                }
              }
            }
          }
        }
      }
    },
    "/ingredients/{id}" : {
      "get" : {
        "summary" : "Get an ingredient by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the ingredient to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns the ingredient with the specified ID",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ingredient"
                }
              }
            }
          }
        }
      },
      "put" : {
        "summary" : "Update an ingredient by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the ingredient to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/IngredientInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Returns the updated ingredient",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ingredient"
                }
              }
            }
          }
        }
      }
    },
    "/recipes" : {
      "get" : {
        "summary" : "Get all recipes",
        "responses" : {
          "200" : {
            "description" : "Returns a list of all recipes",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Recipe"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new recipe",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RecipeInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Returns the newly created recipe",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Recipe"
                }
              }
            }
          }
        }
      }
    },
    "/recipes/{id}" : {
      "get" : {
        "summary" : "Get a recipe by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the recipe to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns the recipe with the specified ID",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Recipe"
                }
              }
            }
          }
        }
      },
      "put" : {
        "summary" : "Update a recipe by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the recipe to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RecipeInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Returns the updated recipe",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Recipe"
                }
              }
            }
          }
        }
      }
    },
    "/recipes/by_ingredient" : {
      "get" : {
        "summary" : "Get all recipes that use a certain ingredient",
        "parameters" : [ {
          "name" : "ingredient",
          "in" : "query",
          "description" : "The name of the ingredient to search for",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns a list of all recipes that use the specified ingredient",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Recipe"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/categories" : {
      "get" : {
        "summary" : "Get all categories",
        "responses" : {
          "200" : {
            "description" : "Returns a list of all categories",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Category"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new category",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CategoryInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Returns the newly created category",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Category"
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}" : {
      "get" : {
        "summary" : "Get a category by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the category to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns the category with the specified ID",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Category"
                }
              }
            }
          }
        }
      },
      "put" : {
        "summary" : "Update a category by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the category to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CategoryInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Returns the updated category",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Category"
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}/recipes" : {
      "get" : {
        "summary" : "Get all recipes in a category",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the category to get the recipes for",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Returns a list of all recipes in the specified category",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Recipe"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "User" : {
        "required" : [ "email", "name" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "The ID of the user"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the user"
          },
          "email" : {
            "type" : "string",
            "description" : "The email address of the user"
          }
        }
      },
      "UserInput" : {
        "required" : [ "email", "name" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "The name of the user"
          },
          "email" : {
            "type" : "string",
            "description" : "The email address of the user"
          }
        }
      },
      "Ingredient" : {
        "required" : [ "name", "quantity" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "The ID of the ingredient"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the ingredient"
          },
          "quantity" : {
            "type" : "string",
            "description" : "The quantity of the ingredient"
          }
        }
      },
      "IngredientInput" : {
        "required" : [ "name", "quantity" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "The name of the ingredient"
          },
          "quantity" : {
            "type" : "string",
            "description" : "The quantity of the ingredient"
          }
        }
      },
      "Recipe" : {
        "required" : [ "instructions", "name", "user_id" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "The ID of the recipe"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the recipe"
          },
          "instructions" : {
            "type" : "string",
            "description" : "The instructions for making the recipe"
          },
          "user_id" : {
            "type" : "integer",
            "description" : "The ID of the user who created the recipe"
          }
        }
      },
      "RecipeInput" : {
        "required" : [ "instructions", "name", "user_id" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "The name of the recipe"
          },
          "instructions" : {
            "type" : "string",
            "description" : "The instructions for making the recipe"
          },
          "user_id" : {
            "type" : "integer",
            "description" : "The ID of the user who created the recipe"
          }
        }
      },
      "Category" : {
        "required" : [ "name" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "The ID of the category"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the category"
          },
          "recipe_ids" : {
            "type" : "array",
            "description" : "The IDs of the recipes in this category",
            "items" : {
              "type" : "integer"
            }
          }
        }
      },
      "CategoryInput" : {
        "required" : [ "name" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "The name of the category"
          }
        }
      }
    }
  }
}